apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ai-arena-mongodb
  labels:
    component: mongodb
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: block.csi.vultr.com
    volumeHandle: {{ .Values.mongodb.volumeHandle }}
    fsType: ext4
