apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendName }}
  labels:
    {{- include "ai-arena.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontendNodePort }}
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.frontendNodePort }}
  selector:
    app: {{ .Values.frontendName }}
