apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-arena-mongodb
  namespace: default
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  selector:
    matchLabels:
      component: mongodb
