{{- if not .Values.localDeployment }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: default
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  selector:
    matchLabels:
      component: prometheus
{{- end }}
